export const students = [
  {
    id: 1,
    name: "Abrar Hossain",
    roll: 101,
    class: "10",
    section: "A",
    marks: { math: 85, physics: 78, chemistry: 82, english: 88 },
  },
  {
    id: 2,
    name: "Nusrat Jahan",
    roll: 102,
    class: "10",
    section: "A",
    marks: { math: 92, physics: 89, chemistry: 94, english: 91 },
  },
  {
    id: 3,
    name: "Rahim Ahmed",
    roll: 103,
    class: "10",
    section: "B",
    marks: { math: 64, physics: 58, chemistry: 61, english: 67 },
  },
  {
    id: 4,
    name: "Ayesha Khan",
    roll: 104,
    class: "10",
    section: "B",
    marks: { math: 45, physics: 52, chemistry: 48, english: 50 },
  },
  {
    id: 5,
    name: "Tanvir Islam",
    roll: 105,
    class: "10",
    section: "A",
    marks: { math: 77, physics: 81, chemistry: 75, english: 73 },
  },
  {
    id: 6,
    name: "Sadia Rahman",
    roll: 106,
    class: "10",
    section: "C",
    marks: { math: 88, physics: 84, chemistry: 86, english: 90 },
  },
  {
    id: 7,
    name: "Hasan Mahmud",
    roll: 107,
    class: "10",
    section: "C",
    marks: { math: 55, physics: 60, chemistry: 58, english: 62 },
  },
  {
    id: 8,
    name: "Farzana Akter",
    roll: 108,
    class: "10",
    section: "A",
    marks: { math: 69, physics: 72, chemistry: 70, english: 74 },
  },
  {
    id: 9,
    name: "Imran Hossain",
    roll: 109,
    class: "10",
    section: "B",
    marks: { math: 81, physics: 79, chemistry: 83, english: 76 },
  },
  {
    id: 10,
    name: "Mim Chowdhury",
    roll: 110,
    class: "10",
    section: "C",
    marks: { math: 91, physics: 93, chemistry: 89, english: 94 },
  },
  {
    id: 11,
    name: "Rafiul Islam",
    roll: 111,
    class: "10",
    section: "A",
    marks: { math: 47, physics: 50, chemistry: 45, english: 52 },
  },
  {
    id: 12,
    name: "Anika Sultana",
    roll: 112,
    class: "10",
    section: "B",
    marks: { math: 74, physics: 71, chemistry: 76, english: 78 },
  },
  {
    id: 13,
    name: "Siam Ahmed",
    roll: 113,
    class: "10",
    section: "C",
    marks: { math: 66, physics: 63, chemistry: 65, english: 68 },
  },
  {
    id: 14,
    name: "Jannatul Ferdous",
    roll: 114,
    class: "10",
    section: "A",
    marks: { math: 89, physics: 86, chemistry: 90, english: 87 },
  },
  {
    id: 15,
    name: "Mahfuz Rahman",
    roll: 115,
    class: "10",
    section: "B",
    marks: { math: 58, physics: 55, chemistry: 60, english: 57 },
  },
  {
    id: 16,
    name: "Tania Akter",
    roll: 116,
    class: "10",
    section: "C",
    marks: { math: 83, physics: 80, chemistry: 82, english: 85 },
  },
  {
    id: 17,
    name: "Arif Hasan",
    roll: 117,
    class: "10",
    section: "A",
    marks: { math: 71, physics: 74, chemistry: 70, english: 72 },
  },
  {
    id: 18,
    name: "Nabila Islam",
    roll: 118,
    class: "10",
    section: "B",
    marks: { math: 95, physics: 92, chemistry: 96, english: 94 },
  },
  {
    id: 19,
    name: "Shakib Al Amin",
    roll: 119,
    class: "10",
    section: "C",
    marks: { math: 62, physics: 59, chemistry: 61, english: 64 },
  },
  {
    id: 20,
    name: "Rumana Haque",
    roll: 120,
    class: "10",
    section: "A",
    marks: { math: 79, physics: 77, chemistry: 80, english: 78 },
  },
];
